spring.application.name=realEstae

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/dumy
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=U2VjcmV0S2V5Q2hhdEdQVF9SYW5kb21fMjAyNl9TZWN1cmU=
jwt.expiration=86400000

#Admin Details
app.admin.email=admin@test.com
app.admin.password=admins123
app.admin.name=Default Admin
app.admin.phone=9999999999

app.admin.street=HQ Street
app.admin.city=Pune
app.admin.state=Maharashtra
app.admin.pincode=411001

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=waghharish54@gmail.com
spring.mail.password=owvh wbsu dakw usyo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true